apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymenthistory
  labels:
    app: paymenthistory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymenthistory
  template:
    metadata:
      labels:
        app: paymenthistory
    spec:
      containers:
        - name: paymenthistory
          image: admin14acr.azurecr.io/pe-bookstore-paymenthistory:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5